# Generated by Django 4.2.1 on 2023-11-23 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_sold_short_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='cgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='igst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='packing_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='sgst',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Proforma_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField(default=0)),
                ('PIDsold', models.BooleanField(default=False)),
                ('req_date', models.DateField()),
                ('sell_price', models.IntegerField(default=0)),
                ('total_non_tax_price', models.IntegerField(default=0)),
                ('packing_charges', models.IntegerField(default=0)),
                ('cgst', models.IntegerField(default=0)),
                ('sgst', models.IntegerField(default=0)),
                ('igst', models.IntegerField(default=0)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('item_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock')),
            ],
        ),
    ]
