# Generated by Django 4.2.1 on 2023-11-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_sold_cgst_sold_igst_sold_packing_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma_invoice',
            name='pleating_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proforma_invoice',
            name='slitting_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='pleating_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='slitting_price',
            field=models.IntegerField(default=0),
        ),
    ]
